# -*- coding: utf-8 -*-
"""Generate docs/t2s.js — a Traditional->Simplified char map covering every
CJK character that appears in docs/data/gma.json, for client-side
Simplified/Traditional display toggle and cross-script search."""
import json
from pathlib import Path
from opencc import OpenCC

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "docs" / "data" / "gma.json"
OUT = ROOT / "docs" / "t2s.js"

cc = OpenCC("t2s")

def walk(obj, chars):
    if isinstance(obj, str):
        chars.update(c for c in obj if "㐀" <= c <= "鿿")
    elif isinstance(obj, list):
        for x in obj:
            walk(x, chars)
    elif isinstance(obj, dict):
        for k, v in obj.items():
            walk(k, chars)
            walk(v, chars)

chars = set()
walk(json.loads(SRC.read_text(encoding="utf-8")), chars)

mapping = {}
for ch in sorted(chars):
    s = cc.convert(ch)
    if s != ch and len(s) == 1:
        mapping[ch] = s

OUT.write_text(
    "// generated by scripts/gen_t2s.py — traditional->simplified char map\n"
    f"var T2S_MAP = {json.dumps(mapping, ensure_ascii=False)};\n",
    encoding="utf-8")
print(f"chars in data: {len(chars)}, mapped pairs: {len(mapping)}, "
      f"wrote {OUT} ({OUT.stat().st_size//1024} KB)")
